export const property = {
  name: 'LivingSpring Apartments',
  tagline: 'A peaceful home in the heart of Sunyani',
  location: 'Sunyani, Bono Region',
  country: 'Ghana',
  address: 'House 12, Fiapre Road, Sunyani',
  description:
    'LivingSpring Apartments offers a calm, comfortable stay in Sunyani — the green, garden city of Ghana\'s Bono Region. Whether you\'re visiting family, working in town, or passing through, you\'ll find a clean, quiet space with everything you need to feel at home. Wake to birdsong, enjoy your morning tea on the porch, and let the warmth of Sunyani welcome you.',
  shortDesc:
    'A clean, quiet, and comfortable apartment in Sunyani — perfect for short or long stays.',
  type: 'Self-contained apartment',
  guests: 4,
  bedrooms: 2,
  bathrooms: 1,
  amenities: [
    'Air conditioning',
    'Free Wi-Fi',
    'Fully equipped kitchen',
    'Private parking',
    '24/7 security',
    'Hot shower',
    'Smart TV',
    'Refrigerator',
    'Washing machine',
    'Garden view',
  ],
  houseRules: [
    'Check-in: 2:00 PM · Check-out: 11:00 AM',
    'No smoking inside the apartment',
    'Pets allowed on request',
    'Quiet hours after 10:00 PM',
  ],
  gallery: [
    'https://images.pexels.com/photos/8089172/pexels-photo-8089172.jpeg?auto=compress&cs=tinysrgb&w=1600',
    'https://images.pexels.com/photos/6782479/pexels-photo-6782479.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/7166645/pexels-photo-7166645.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/8089268/pexels-photo-8089268.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/6957081/pexels-photo-6957081.jpeg?auto=compress&cs=tinysrgb&w=1200',
    'https://images.pexels.com/photos/157117/pexels-photo-157117.jpeg?auto=compress&cs=tinysrgb&w=1200',
  ],
  heroImage: 'https://images.pexels.com/photos/8089172/pexels-photo-8089172.jpeg?auto=compress&cs=tinysrgb&w=2000',
  exteriorImage: 'https://images.pexels.com/photos/11631278/pexels-photo-11631278.jpeg?auto=compress&cs=tinysrgb&w=1200',
  host: {
    name: 'Mr. Owusu',
    role: 'Your host',
    image: 'https://images.pexels.com/photos/30208144/pexels-photo-30208144.jpeg?auto=compress&cs=tinysrgb&w=300',
    bio: 'A welcoming host who takes pride in making every guest feel at home. Mr. Owusu is available by phone for anything you need during your stay.',
  },
  contact: {
    phone: '+233 50 123 4567',
    whatsapp: '+233 50 123 4567',
    email: 'stay@livingspring.gh',
  },
  reviews: [
    { name: 'Akua M.', date: 'July 2026', rating: 5, text: 'A beautiful, clean apartment in a quiet part of Sunyani. Mr. Owusu was so welcoming. I felt at home immediately.' },
    { name: 'David K.', date: 'June 2026', rating: 5, text: 'Perfect for my work trip. Fast Wi-Fi, comfortable bed, and easy parking. Will definitely stay again.' },
    { name: 'Sarah B.', date: 'May 2026', rating: 5, text: 'The garden view in the morning is lovely. The apartment has everything you need. Highly recommended.' },
  ],
  lat: 7.3405,
  lng: -2.3263,
}
